[tool.black]
line-length = 88

[tool.mypy]
mypy_path = "./src"
ignore_missing_imports = true
exclude = [
    '0017_merge_0016_alter_ad_options_0016_alter_category_image\.py',
    '0020_merge_20250707_1003\.py',
    '0001_initial\.py',
]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = [
    "__pycache__",
    ".venv",
    "src/users/migrations",
    "src/categories/migrations",
    "src/chats/migrations",
    "src/ads/migrations",
    "src/services/migrations",
    "src/notifications/migrations",
]
[tool.ruff.lint]
ignore = ["D100", "D102", "D104", "RUF002", "RUF001", "COM812"]
select = ["ALL"]
# Исключить папки из проверок
exclude = [
    "__pycache__",
    ".venv",
    "migrations/.*"
]
[tool.ruff.lint.pydocstyle]
convention = "google"
[tool.ruff.format]
quote-style = "double"
[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"